repos:
  # Ruff: Fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      # Ruff linter (replaces flake8, autoflake, and other linters)
      - id: ruff
        name: ruff check
        args: [
          --fix,
          --exit-non-zero-on-fix,
        ]
        types_or: [python, pyi, jupyter]
      
      # Ruff formatter (replaces black)
      - id: ruff-format
        name: ruff format
        types_or: [python, pyi, jupyter]

  # mypy: 정적 타입 검사 (선택사항 - ruff는 타입 검사를 하지 않음)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.13.0
  #   hooks:
  #     - id: mypy
  #       args: [--config-file=pyproject.toml]
  #       additional_dependencies: [types-requests]
  #       files: \.py$
  #       require_serial: true